env:
  browser: true
  commonjs: true
  es2021: true
  node: true
  jest/globals: true
extends:
  - airbnb-base
  - prettier
parserOptions:
  ecmaVersion: 13
  sourceType: module
plugins:
  - jest
rules:
  import/prefer-default-export: off
  import/extensions: off
  implicit-arrow-linebreak: 0
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
