'extends': '@linthtml/linthtml-config-recommended'
maxerr: false
text-ignore-regex: false
raw-ignore-regex: false
attr-name-ignore-regex: false
id-class-ignore-regex: false
line-max-len-ignore-regex: false
rules:
  attr-quote-style:
    - true
    - double
  id-style:
    - true
    - bem
  class-style:
    - true
    - bem
  indent-width:
    - true
    - 2
  label-req-for: true
  line-end-style:
    - true
    - lf
  line-max-len:
    - true
    - 120
  title-max-len:
    - true
    - 60
